#Default config for v0.4-BETA
#             ___              _       _         __  __               Our plugins: https://alonsoaliaga.com/plugins
#            | _ \_  _ _ _  __| |_  __| |_ __ _ / _|/ _|              Support server: https://alonsoaliaga.com/discord
#            |  _/ || | ' \/ _| ' \(_-<  _/ _` |  _|  _|              Youtube: https://alonsoaliaga.com/play
#            |_|  \_,_|_||_\__|_||_/__/\__\__,_|_| |_|                Test server: plugins.alonsoaliaga.com
#                          by AlonsoAliaga                            Twitch: https://alonsoaliaga.com/twitch
#       Considering donating? https://alonsoaliaga.com/donate         Thanks for downloading my plugin <3.
# ======================================================================================================================================
# |              Downloaded this jar in a server setup? Tell the author he is NOT allowed to upload someone else work!                 |
# |   Update to latest version as soon as possible. Support WON'T be given when using old versions. Specially from downloaded setups.  |
# | Remember: Support is only provided for .jar files downloaded DIRECTLY from spigotmc.org! Other files will be considered as invalid |
# |        as they are NOT the same .jar file the developer (me) uploaded and I cannot guarantee that the file is safe or not.         |
# |                   If you have issues with setup configs. Tell the setup author to update his config file.                          |
# ======================================================================================================================================
Messages:
  No-permission: "&cYou don't have permission to do this."
  Reloaded: "&aSome messages and options have been reloaded. Other may require a restart!"
  Please-reconnect: "&cYou became staff recently. Please reconnect to the server to use this command!"
  Invalid-player: "&cPlayer is not online!"
  Connected-disabled: "&cPunch staff is disabled, make sure you enable it when you are done with the important things!"
  Toggle:
    No-permission: "&cYou don't have permission to do this. Only admins can do this!"
    Enabled: "&aYou can now be punched by donors!"
    Disabled: "&cYou cannot be punched by donors now. You must be doing something important to disable this.."
  Punch:
    Staff-disabled: "&cThis staff member is doing some really important things right now!"
    New-staff: "&cThis member just became staff. He cannot be punched for now :("
    New-donor: "&cYou just became a donor. Please, reconnect to the server!"
    Someone-tried-to-punch: "&cSomeone tried to punch you. Please reconnect to the server!"
    Donor-cooldown: "&cYou just punched a staff recently, try again in {TIME}."
    Staff-cooldown: "&cThis staff was punched recently, try again in {TIME}."
  Punched:
    Placeholder:
      #Placeholders are available here. ONLY HERE. You can use the placeholder {PLAYER} to replace with player name.
      Puncher: "%vault_prefix% {PLAYER}" #This will display something like: "[VIP] AlonsoAliaga"
      Punched: "%vault_prefix% {PLAYER}" #This will display something like: "[ADMIN] AlonsoAliaga"
    #PlaceholderAPI is NOT AVAILABLE HERE. WHY??? Because internally we need to define the player to get placeholders.
    #And since there will be 2 players mentioned in the message (staff and donor) plugin won't know who to choose.
    #Use Placeholder section above to specify a placeholder to display with the name.
    # {PUNCHER} will be replaced with the placeholder in "Puncher" above.
    # {PUNCHED} will be replaced with the placeholder in "Punched" above.
    Broadcast:
    - "&f{PUNCHER}&7 yeeted &f{PUNCHED}&7 into the sky!"
    - "&f{PUNCHER}&7 smashed &f{PUNCHED}&7 into the sky!"
    - "&f{PUNCHER}&7 sent &f{PUNCHED}&7 on a space voyage!"
    - "&f{PUNCHER}&7 gave &f{PUNCHED}&7 a bird's eye view!"
    - "&f{PUNCHER}&7 kicked &f{PUNCHED}&7 off the ground!"
    - "&f{PUNCHER}&7 knocked &f{PUNCHED}&7 off the world!"
  WorldGuard:
    #Set it to "" to disable this message.
    Disabled-region: "&cYou cannot punch staffs in this region!"
  Help:
    Admin:
    - "&4 /punchstaff toggle &f- &7Toggle punch status"
    - "&4 /punchstaff reload &f- &7Reload configuration"
    Staff:
    - "&4 /punchstaff toggle &f- &7Toggle punch status"
    User: []

Options:
  #Debug mode, enable ONLY if developer asks you to do it, otherwise you might get a nice spam in chat and console.
  Debug-mode: false
  #Power to launch the staff in the air.
  Power: 4.0
  #If true, player will be instantly punched in the air.
  #If false, player will be punched in the air AFTER 2 seconds.
  #Recommended to leave it as false. Looks way better.
  Instant: false
  #Cooldown in seconds before a Staff can be punched again.
  Cooldown-staff: 15 #Default 600
  #Cooldown in seconds before a donor can punch a staff again.
  Cooldown-donor: 10 #Default 300
  #If false, message will be sent to all players in the same world where the staff was punched.
  #If true, message will be sent to all players ignoring world.
  Global-broadcast: true
  Checks:
    #This prevents players to punch players they CANNOT see. (This doesn't include invisibility potion, only model)
    Invisibility: true
    #This prevents players to punch players with "vanish" and "vanished" metadata tag. (Most vanish plugins use this)
    Vanish-tag: true
    #This prevents players to punch players with "NPC" metadata tag
    Npc-tag: true
  #Worlds in which punch staff will be enabled.
  Enabled-worlds:
  - "world"
  - "world_shop"
  - "lobby"
  #This is the amount of ticks the plugin will wait before loading data.
  #Useful if your have issues with players "losing" their stats on server change or reconnect.
  #Set to 0 to disable. If enabled, it's like that some plugins that send messages on join will not fetch correct data from placeholders.
  #To "fix" this use this plugin made by our team which adds messages on player join with an option to set delay.
  #We also support placeholder check to prevent message to be sent when player is in vanish mode. (Using placeholder to check if player is vanished)
  #Check our plugin on https://alonsoaliaga.com/AlonsoJoin (If available)
  Data-delay: 20
  WorldGuard:
    Warning:
    - "Default flag:"
    - " This is the default behavior if the flag is not specified BUT you are inside in a WorldGuard region."
    - "  true - Players can punch staffs."
    - "  false - Players cannot punch staffs."
    Default-flag: true

Permissions:
  Admin: "alonsoaliaga.punchstaff.admin"
  #Permission required to be recognized as donor and be able to punch staffs.
  #Set to "none" to disable permission and make ALL players be able to punch staffs.
  Donor: "alonsoaliaga.punchstaff.donor"
  #Permission required to be recognized as staff and be able to BE punched by donors.
  #Set to "none" to disable permission and make ALL players be able to be punched by donors. NOT RECOMMENDED!
  Staff: "alonsoaliaga.punchstaff.staff"
  #Permission for staffs to toggle status so they can/cannot be punched. (In case they are doing important things and they can't be annoyed)
  #Set to "none" to disable, all staffs will be able to perform to toggle status.
  Toggle: "alonsoaliaga.punchstaff.toggle"

Database:
  #Available types: MySQL and SQLite
  #You can use MySQL to make it global or you can use SQLite to make it local.
  #MySQL requires a server (local or external)
  #SQLite doesn't require anything, it's saved in a db file in the folder.
  #By default HikariCP is used for MySQL, if you really want to use MySQL and NO HIKARICP, set Type to "IWantMySQL"
  Type: "SQLite"
  Table: "punchstaff"
  #If type is SQLite
  File: "database-punchstaff"
  #If type is MySQL
  Host: 127.0.0.1
  Port: 3306
  Database: "punchstaff"
  Username: "root"
  Password: "12345"
  #Modify this just if you know what you are doing.
  #This will be added at the end of database url (Not in SQLITE, only in IWantMySQL).
  #Useful if you want to set useSSL or autoReconnect or any other modifier.
  #This option is no longer used as HikariCP was implemented. Please use "HikariCP.Source-properties" options.
  Additional-url: "?useSSL=false"
  #This option has been added to prevent connection timeout.
  #Time is in minutes. Every X minutes the plugin will run a test query to keep connection alive.
  #This option is no longer used as HikariCP was implemented.
  Keep-connection-interval: 30
  HikariCP:
    Warning:
    - "========================================================================================"
    - "You don't need to edit this text, it's ONLY displayed in config so you can read it."
    - "========================================================================================"
    - "HikariCP is experimental. Remember that only modify the following IF YOU KNOW HOW IT WORKS."
    - "If you don't want to use HikariCP and want the usually MySQL set Type to \"IWantMySQL\""
    - "You will not get support for HikariCP configurations as 1) I'm not a HikariCP advanced user"
    - "and 2) Customization depends on the owner and his knowledge level."
    - "Related to Source-properties, if you KNOW and want to add custom properties follow the format:"
    - "Source-properties:"
    - '  thePropertySelected1: "theValue1"'
    - '  thePropertySelected2: "theValue2"'
    - "[!] Remember to modify data only if you know what you are doing."
    - "Available source properties can be found here: https://alonsoaliaga.com/HikariCP-sp"
    - "Available source class names can be found here: https://alonsoaliaga.com/HikariCP-cn"
    Max-pool-size: 3
    #Set your custom source class name ONLY IF YOU KNOW WHAT IT IS.
    Custom-source-class-name: "default"
    #This is the source properties to modify your HikariCP configurations.
    #It allows you to select and specify custom configs IF YOU KNOW WHAT YOU ARE DOING.
    #Source properties can be found here: https://links.alonsoaliaga.com/HikariCP-sp
    Source-properties: []

Updates:
  #Auto update configuration? Enabling will delete comments.
  Auto-update-configuration: true
  #Check for updates? Recommended to keep it enabled.
  Check-updates: true
  #Notify updates when player with permission joins the server?
  Notify-updates: true
  #Permission required to receive update message.
  Permission: "alonsoaliaga.punchstaff.update"
  #Message to send when update is found.
  Message: "&4[PunchStaff] &eA new update has been found! You are using version {CURRENT}. Download version {NEW} here &c{LINK}"
